---
title: "Kenya Uptake Descriptive Analysis"
author: "Andrew Mertens"
date: "December 15, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}

#---------------------------------------
# uptake.R
#
# andrew mertens amertens@berkeley.edu)
#
# summarize measures of uptake / compliance
# by study arm and measurement round
# (enrollment, year 1, year 2)
#---------------------------------------

#---------------------------------------
# input files:
#	washb-kenya-uptake.csv
#
# output files:
# kenya-uptake.RData
#
#---------------------------------------


#---------------------------------------
# preamble
#---------------------------------------
rm(list=ls())
try(detach(package:plyr))
library(dplyr)
library(washb)
library(foreign)


#wrapper function to call washb_mean
mean.est <- function(Y,tr,svy,id,group="Control",s=0,print=FALSE) {
  # Y : outcome variable
  # tr: treatment indicator variable
  # svy  : measurment round variable
  # id: cluster ID variable
  # group : string. treatment factor level to compute mean
  # s     : survey round to compute mean. 0, 1, or 2
  require(washb)
  dat <- data.frame(id=id[tr==group & svy==s],
                        svy=svy[tr==group & svy==s],
                        Y=Y[tr==group & svy==s],
                        tr=tr[tr==group & svy==s])
  dat <- dat[complete.cases(dat),]
  fit <- washb_mean(Y=dat$Y,
                 id=dat$id,
                 print=F
                 )
  if(print==TRUE) print(fit)
  res<-fit[c(2,5,6)]
  names(res) <- c("mean","ci.lb","ci.ub")
  return(res)
}



#---------------------------------------
# load the uptake analysis dataset
#---------------------------------------
setwd("C:/Users/andre/Dropbox/WBK-primary-analysis/Data/Final/Andrew")
#d <- read.csv("washb-kenya-uptake.csv")
d <- read.dta("washb-kenya-uptake.dta")
```

```{r}


#create 2 empty rows to add for midline and endline passive control, so empty columns get added to the table
d[(nrow(d)+1),]<-rep(NA,ncol(d))
d[(nrow(d)+1),]<-rep(NA,ncol(d))
d[(nrow(d)-1),4]<-"Passive Control"
d[(nrow(d)),4]<-"Passive Control"
d[(nrow(d)-1),"studyyear"]<-1
d[(nrow(d)),"studyyear"]<-2
tail(d)



# re-order the treatment factor for convenience
d$tr <- factor(d$tr,levels=c("Control","Passive Control","Water","Sanitation","Handwashing","WSH","Nutrition","Nutrition + WSH"))

#---------------------------------------
# for each uptake indicator, summarize
# the number of obs and the % at each
# measurement round
#---------------------------------------

d.svy <- group_by(d, tr,studyyear)



# promoter visit
promoter_vis <- summarise(d.svy,n=sum(!is.na(promoter_vis)),count=sum(promoter_vis,na.rm=T),mean=mean(promoter_vis,na.rm=T))
print(promoter_vis, n=24)

# store water with detectable chlorine
freechl <- summarise(d.svy,n=sum(!is.na(freechl)),count=sum(freechl,na.rm=T),mean=mean(freechl,na.rm=T))
print(freechl, n=24)

# access to improved latrine
impr_lat <- summarise(d.svy,n=sum(!is.na(impr_lat)),count=sum(impr_lat,na.rm=T),mean=mean(impr_lat,na.rm=T))
print(impr_lat, n=24)

# Child feces safetly disposed
ch_feces_safe_disp <- summarise(d.svy,n=sum(!is.na(ch_feces_safe_disp)),count=sum(ch_feces_safe_disp,na.rm=T),mean=mean(ch_feces_safe_disp,na.rm=T))
print(ch_feces_safe_disp, n=24)

# handwashing location has water and soap
watsoap_avail <- summarise(d.svy,n=sum(!is.na(watsoap_avail)),count=sum(watsoap_avail,na.rm=T),mean=mean(watsoap_avail,na.rm=T))
print(watsoap_avail, n=24)

# Mean sachets of LNS fed in prior week to index child 6-24 mos
lnsp <- summarise(d.svy,n=sum(!is.na(lnsp)),mean=mean(lnsp,na.rm=T))
print(lnsp, n=24)



#---------------------------------------
# combine estimates into a single matrix that matches Jade's
#---------------------------------------
uptake.tabn <- as.data.frame(
  rbind(
    promoter_vis$n,
    freechl$n,
    impr_lat$n,
    ch_feces_safe_disp$n,
    watsoap_avail$n,
    lnsp$n
))
uptake.tabmean <- as.data.frame(
  rbind(
  promoter_vis$mean,
  freechl$mean,
  impr_lat$mean,
  ch_feces_safe_disp$mean,
  watsoap_avail$mean,
  lnsp$mean
))
names(uptake.tabn) <- paste(rep(levels(d$tr),rep(3,8)),c("0 n","1 n","2 n"))
names(uptake.tabmean) <- paste(rep(levels(d$tr),rep(3,8)),c("0 ave","1 ave","2 ave"))



uptake.tab<-cbind(uptake.tabn[,1],uptake.tabmean[,1])
for(i in 2:(ncol(uptake.tabn))){
  uptake.tab<-cbind(uptake.tab,uptake.tabn[,i],uptake.tabmean[,i])
}
uptake.tab<-as.data.frame(uptake.tab)
names(uptake.tab) <- paste(rep(levels(d$tr),rep(6,8)),c("0 n","0 ave","1 n","1 ave","2 n","2 ave"))
uptake.tab$label<-c(
  "Promoter visit",
  "Store water with detectable free chlorine",
  "Access to improved latrine",
  "Child feces safetly disposed",
  "Primary handwashing station has water and soap",
  "LNS sachet consumption % of expected"
)

# reorder label
uptake_table_A <- uptake.tab[,c(ncol(uptake.tab),1:(ncol(uptake.tab)-1))]

# print table
uptake_table_A


```

